load("@rules_cc//cc:defs.bzl", "cc_library")

package(
    default_visibility = [
				"//compute:__subpackages__",
				"//storage:__subpackages__",
    ],
)

cc_library(
    name = "parser",
    srcs = ["parser.cc"],
    hdrs = ["parser.h"],
)
